{{- if and .Values.serviceMonitor.enabled .Values.config.Metrics "prometheus" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "refinery.fullname" . }}
  labels:
    {{- include "refinery.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "refinery.labels" . | nindent 6 }}
  endpoints:
  - port: "metrics"
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    path: "/metrics"
{{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.serviceMonitor.metricRelabelings | indent 6) . }}
{{- end }}
{{- if .Values.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.serviceMonitor.relabelings | indent 6 }}
{{- end }}
{{- end }}